"""Provider-neutral LLM contracts and the default OpenAI compatibility facade."""

from uptick_agent.llm.contracts import (
    GenerationSettings,
    LlmAuthenticationError,
    LlmCallTelemetry,
    LlmCapabilities,
    LlmClient,
    LlmConfigurationError,
    LlmError,
    LlmMessage,
    LlmPermanentProviderError,
    LlmProviderError,
    LlmRateLimitError,
    LlmStructuredOutputError,
    LlmTransientError,
    LlmUnsupportedCapabilityError,
    ReasoningEffort,
    StructuredGenerationRequest,
    StructuredGenerationResult,
    TextGenerationRequest,
    TextGenerationResult,
    serialize_structured_generation_request,
)
from uptick_agent.llm.openai import OpenAIProviderFactory, OpenAISGRModel
from uptick_agent.llm.registry import LlmProviderConfig, LlmProviderFactory, LlmProviderRegistry

__all__ = [
    "GenerationSettings",
    "LlmCapabilities",
    "LlmClient",
    "LlmConfigurationError",
    "LlmError",
    "LlmAuthenticationError",
    "LlmCallTelemetry",
    "LlmMessage",
    "LlmProviderConfig",
    "LlmProviderError",
    "LlmPermanentProviderError",
    "LlmRateLimitError",
    "ReasoningEffort",
    "LlmProviderFactory",
    "LlmProviderRegistry",
    "LlmStructuredOutputError",
    "LlmUnsupportedCapabilityError",
    "LlmTransientError",
    "OpenAIProviderFactory",
    "OpenAISGRModel",
    "StructuredGenerationRequest",
    "StructuredGenerationResult",
    "TextGenerationRequest",
    "TextGenerationResult",
    "serialize_structured_generation_request",
]
